
export const characters = [
    {id: "Ame", name: "Amelia Watson", weapon: "Pistol Shot"},
    {id: "Gaw", name: "Gawr Gura", weapon: "Trident Thrust"},
    {id: "Nin", name: "Ninomae Ina'nis", weapon: "Summon Tentacle"},
    {id: "Tak", name: "Takanashi Kiara", weapon: "Phoenix Sword"},
    {id: "Cal", name: "Calliope Mori", weapon: "Scythe Swing"},
    {id: "Hak", name: "Hakos Baelz", weapon: "Play Dice"},
    {id: "Our", name: "Ouro Kronii", weapon: "Clock Hands"},
    {id: "Cer", name: "Ceres Fauna", weapon: "Nature"},
    {id: "Nan", name: "Nanashi Mumei", weapon: "Bird Feather"},
    {id: "Tsu", name: "Tsukumo Sana", weapon: "Orbit"},
    {id: "IRy", name: "IRyS", weapon: "Nephilim Blast"},
    {id: "Shi", name: "Shirakima Fubuki", weapon: "Fox Tail"},
    {id: "Ook", name: "Ookami Mio", weapon: "Tarot Cards"},
    {id: "Nek", name: "Nekomata Okayu", weapon: "Onigiri"},
    {id: "Ing", name: "Inugami Korone", weapon: "Orayo!"},
    {id: "Tok", name: "Tokino Sora", weapon: "Bright Star"},
    {id: "AZK", name: "AZKi", weapon: "Dive Song"},
    {id: "Rob", name: "Roboco-san", weapon: "Hi-Spec Pistol"},
    {id: "Hos", name: "Hoshimachi Suisei", weapon: "Axe Swing"},
    {id: "Sak", name: "Sakura Miko", weapon: "Sakura Gohei"},
    {id: "Aka", name: "Akai Haato", weapon: "Red Heart"},
    {id: "Yaz", name: "Yazora Mel", weapon: "Kapu Kapu"},
    {id: "Nat", name: "Natsuiro Matsuri", weapon: "Ebifrion"},
    {id: "Aki", name: "Aki Rosenthal", weapon: "Aik"},
    {id: "Ooz", name: "Oozora Subaru", weapon: "Baseball Pitch"},
    {id: "Yuz", name: "Yuzuki Choco", weapon: "Love Needle"},
    {id: "Mur", name: "Murasaki Shion", weapon: "Murasaki Bolt"},
    {id: "Nak", name: "Nakiri Ayame", weapon: "Dual Katana"},
    {id: "Min", name: "Minato Aqua", weapon: "Cleaning Broom"},
    {id: "Air", name: "Airani lofifteen", weapon: "Paint Brush"},
    {id: "Moo", name: "Moona Hoshinova", weapon: "Crescent Moon"},
    {id: "Ayu", name: "Ayunda Risu", weapon: "Nuts"},
    {id: "Kur", name: "Kureiji Ollie", weapon: "Path of Sincerity"},
    {id: "Pav", name: "Pavolia Reine", weapon: "Peafowl Feathers"},
    {id: "Any", name: "Anya Melfissa", weapon: "Keris"},
    {id: "Kob", name: "Kobo Kanaeru", weapon: "Umbrella"},
    {id: "Kae", name: "Kaela Kovalskia", weapon: "Blacksmith Hammer"},
    {id: "Ves", name: "Vestia Zeta", weapon: "Silencer Pistol"},
]

export const weapons = [
    {id: "Spi", name: "Spider Cooking", weapons: ["Bro", "Eld", "ElC", "Jin"]},
    {id: "ElB", name: "Elite Lava Bucket", weapons: ["ElC", "MiC", "Mik", "Jin"]},
    {id: "CEO", name: "CEO's Tears", weapons: ["Bro", "Rin", "Str"]},
    {id: "Wam", name: "Wamy Water", weapons: ["Fro", "SnF", "SnQ"]},
    {id: "HoB", name: "Holo Bomb", weapons: ["Bre", "Fla", "ImD"]},
    {id: "Psy", name: "Psycho Axe", weapons: ["FLF", "Cre", "MiC"]},
    {id: "BLB", name: "BL Book", weapons: ["FLF", "Fro", "Leg"]},
    {id: "Cut", name: "Cutting Board", weapons: ["Abs", "Bon", "Fla"]},
    {id: "Fan", name: "Fan Beam", weapons: ["Dra", "LiB", "Str", "HoF"]},
    {id: "Plu", name: "Plug Type Asacoco", weapons: ["Bre", "Dra", "LiW", "HoF"]},
    {id: "Glo", name: "Glowstick", weapons: ["IdC", "LiB", "SnF", "IdL", "SnQ"]},
    {id: "XPo", name: "X-Potato", weapons: ["ImD", "MiK", "Rap"]},
    {id: "IdS", name: "Idol Song", weapons: ["Cre", "IdC", "Rap", "IdL"]},
    {id: "ENC", name: "EN's Curse", weapons: ["Bon", "Cur", "Eld"]},
    {id: "Bou", name: "Bounce Ball", weapons: ["Abs", "Cur", "Rin"]},
    {id: "Sau", name: "Sausage", weapons: ["Leg", "LiW"]},

    {id: "Abs", name: "Absolute Wall", weapons: ["Bou", "Cut"]},
    {id: "FLF", name: "FL Fujoshi", weapons: ["BLB", "Psy"]},
    {id: "Bon", name: "Bone Bros.", weapons: ["Cut", "ENC"]},
    {id: "Bre", name: "Breath-In Type Asacoco", weapons: ["HoB", "Plu"]},
    {id: "Bro", name: "Broken Dreams", weapons: ["CEO", "Spi"]},
    {id: "Cre", name: "Crescent Bardiche", weapons: ["IdS", "Psy"]},
    {id: "Cur", name: "Curse Ball", weapons: ["Bou", "ENC"]},
    {id: "Dra", name: "Dragon Fire", weapons: ["Fan", "Plu", "HoF"]},
    {id: "Eld", name: "Eldritch Horror", weapons: ["ENC", "Spi"]},
    {id: "ElC", name: "Elite Cooking", weapons: ["ElB", "Spi", "Jin"]},
    {id: "Fla", name: "Flattening Board", weapons: ["Cut", "HoB"]},
    {id: "Fro", name: "Frozen Sea", weapons: ["BLB", "Wam"]},
    {id: "IdC", name: "Idol Concert", weapons: ["Glo", "IdS", "IdL"]},
    {id: "ImD", name: "I'm Die, Thank You Forever", weapons: ["HoB", "XPo"]},
    {id: "Leg", name: "Legendary Sausage", weapons: ["BLB", "Sau"]},
    {id: "LiB", name: "Light Beam", weapons: ["Fan", "Glo"]},
    {id: "LiW", name: "Lightning Wiener", weapons: ["Plu", "Sau"]},
    {id: "MiC", name: "MiComent", weapons: ["ElB", "Psy"]},
    {id: "MiK", name: "MiKorone", weapons: ["ElB", "XPo"]},
    {id: "Rap", name: "Rap Dog", weapons: ["IdS", "XPo"]},
    {id: "Rin", name: "Ring Of Fitness", weapons: ["Bou", "CEO"]},
    {id: "SnF", name: "Snow Flow Sake", weapons: ["Glo", "Wam", "SnQ"]},
    {id: "Str", name: "Stream of Tears", weapons: ["CEO", "Fan"]},

    {id: "HoF", name: "Holy Fire", weapons: ["Dra", "Fan", "Plu"], item: "Gor"},
    {id: "IdL", name: "Idol Live", weapons: ["IdC", "Glo", "IdS"], item: "Ido"},
    {id: "Jin", name: "Jingisukan", weapons: ["ElC", "ElB", "Spi"], item: "Ube"},
    {id: "SnQ", name: "Snow Queen", weapons: ["SnF", "Glo", "Wam"], item: "Sak"},
]

export const items = [
    {id: "Sak", name: "Sake"},
    {id: "Lim", name: "Limiter"},
    {id: "Bod", name: "Body Pillow"},
    {id: "Inj", name: "Injection Type Asacoco"},
    {id: "Cre", name: "Credit Card"},
    {id: "Hal", name: "Halu"},
    {id: "Kni", name: "Knightly Milk"},
    {id: "Fac", name: "Face Mask"},
    {id: "Plu", name: "Plushie"},
    {id: "Nur", name: "Nurse's Horn"},
    {id: "Ful", name: "Full Meal"},
    {id: "Mem", name: "Membership"},
    {id: "Pik", name: "Piki Piki Piman"},
    {id: "Hea", name: "Headphones"},
    {id: "Chi", name: "Chicken's Feather"},
    {id: "Gor", name: "Gorilla's Paw"},
    {id: "Ube", name: "Uber Sheep"},
    {id: "Ido", name: "Idol Costume"},
    {id: "Sto", name: "Stolen Piggy Bank"},
    {id: "Stu", name: "Study Glasses"},
    {id: "Jus", name: "Just Bandage"},
    {id: "GWS", name: "GWS Pill"},
    {id: "Sup", name: "Super Chatto Time!"},
    {id: "Bre", name: "Breastplate"},
    {id: "Hop", name: "Hope Soda"},
    {id: "Kus", name: "Kusogaki Shackles"},
    {id: "Dev", name: "Devil Hat"},
    {id: "Bla", name: "Blacksmith's Gear"},
    {id: "Foc", name: "Focus Shades"},
    {id: "Nin", name: "Ninja Headband"},
    {id: "Res", name: "Researcher's Coat"},
    {id: "Can", name: "Candy Kingdom Sweets"},
    {id: "Bee", name: "Beetle"},
]

export const stamps = [
    {id: "ATK", name: "ATK Up Stamp"},
    {id: "Bom", name: "Bomb Stamp"},
    {id: "Col", name: "Cold Stamp"},
    {id: "Cri", name: "Crit Up Stamp"},
    {id: "Gre", name: "Greed Stamp"},
    {id: "Has", name: "Haste Up Stamp"},
    {id: "Kno", name: "Knockback Stamp"},
    {id: "Lif", name: "Life Steal Stamp"},
    {id: "Lig", name: "Lightness Stamp"},
    {id: "Mar", name: "Marking Stamp"},
    {id: "Pac", name: "Pacifist Stamp"},
    {id: "Pro", name: "Projectile Up Stamp"},
    {id: "Rev", name: "Reverse Stamp"},
    {id: "RGB", name: "RGB Stamp"},
    {id: "Siz", name: "Size Up Stamp"},
    {id: "Slo", name: "Slow Stamp"},
    {id: "Sol", name: "Solo Stamp"},
    {id: "Tru", name: "Trumpet Stamp"},
    {id: "Uni", name: "Unit Stamp"},
    {id: "Wea", name: "Weaken Stamp"},
]
