
export const characters = [
    {id: "Ame", name: "🔍 Amelia Watson", weapon: {name: "Pistol Shot", icon: "Pistol_Shot"}},
    {id: "Gaw", name: "🦈 Gawr Gura", weapon: {name: "Trident Thrust", icon: "Trident_Thrust"}},
    {id: "Nin", name: "🐙 Ninomae Ina'nis", weapon: {name: "Summon Tentacle", icon: "Summon_Tentacle"}},
    {id: "Tak", name: "🐔 Takanashi Kiara", weapon: {name: "Phoenix Sword", icon: "Phoenix_Sword"}},
    {id: "Cal", name: "💀 Calliope Mori", weapon: {name: "Scythe Swing", icon: "Scythe_Swing"}},
    {id: "Hak", name: "🐀 Hakos Baelz", weapon: {name: "Play Dice", icon: "Play_Dice"}},
    {id: "Our", name: "⏰ Ouro Kronii", weapon: {name: "Clock Hands", icon: "Clock_Hands"}},
    {id: "Cer", name: "🌱 Ceres Fauna", weapon: {name: "Nature Shield", icon: "Nature_Shield"}},
    {id: "Nan", name: "🦉 Nanashi Mumei", weapon: {name: "Bird Feather", icon: "Bird_Feather"}},
    {id: "Tsu", name: "🪐 Tsukumo Sana", weapon: {name: "Orbit", icon: "Orbit"}},
    {id: "IRy", name: "🪽  IRyS", weapon: {name: "Nephilim Blast", icon: "Nephilim_Blast"}},
    {id: "Shi", name: "🦊 Shirakima Fubuki", weapon: {name: "Fox Tail", icon: "Fox_Tail"}},
    {id: "Ook", name: "🐺 Ookami Mio", weapon: {name: "Tarot Cards", icon: "Tarot_Cards"}},
    {id: "Nek", name: "🐱 Nekomata Okayu", weapon: {name: "Onigiri", icon: "Onigiri"}},
    {id: "Inu", name: "🐶 Inugami Korone", weapon: {name: "Orayo!", icon: "Orayo"}},
    {id: "Tok", name: "⭐ Tokino Sora", weapon: {name: "Bright Star", icon: "Bright_Star"}},
    {id: "AZK", name: "🎵 AZKi", weapon: {name: "Diva Song", icon: "Diva_Song"}},
    {id: "Rob", name: "🤖 Roboco-san", weapon: {name: "Hi-Spec Pistol", icon: "Hi-Spec_Pistol"}},
    {id: "Hos", name: "🪓 Hoshimachi Suisei", weapon: {name: "Axe Swing", icon: "Axe_Swing"}},
    {id: "Sak", name: "⛩️  Sakura Miko", weapon: {name: "Sakura Gohei", icon: "Sakura_Gohei"}},
    {id: "Aka", name: "❤️ Akai Haato", weapon: {name: "Red Heart", icon: "Red_Heart"}},
    {id: "Yoz", name: "🧛 Yozora Mel", weapon: {name: "Kapu Kapu", icon: "Kapu_Kapu"}},
    {id: "Nat", name: "🥁 Natsuiro Matsuri", weapon: {name: "Ebifrion", icon: "Ebifrion"}},
    {id: "Aki", name: "💪 Aki Rosenthal", weapon: {name: "Aik", icon: "Aik"}},
    {id: "Ooz", name: "🦆 Oozora Subaru", weapon: {name: "Baseball Pitch", icon: "Baseball_Pitch"}},
    {id: "Yuz", name: "💉 Yuzuki Choco", weapon: {name: "Love Needle", icon: "Love_Needle"}},
    {id: "Mur", name: "🧙 Murasaki Shion", weapon: {name: "Murasaki Bolt", icon: "Murasaki_Bolt"}},
    {id: "Nak", name: "👺 Nakiri Ayame", weapon: {name: "Dual Katana", icon: "Dual_Katana"}},
    {id: "Min", name: "🧹 Minato Aqua", weapon: {name: "Cleaning Broom", icon: "Cleaning_Broom"}},
    {id: "Air", name: "🖌️  Airani lofifteen", weapon: {name: "Paint Brush", icon: "Paint_Brush"}},
    {id: "Moo", name: "🌙 Moona Hoshinova", weapon: {name: "Crescent Moon", icon: "Crescent_Moon"}},
    {id: "Ayu", name: "🌰 Ayunda Risu", weapon: {name: "Nuts", icon: "Nuts"}},
    {id: "Kur", name: "🧟 Kureiji Ollie", weapon: {name: "Path of Sincerity", icon: "Path_of_Sincerity"}},
    {id: "Pav", name: "🦚 Pavolia Reine", weapon: {name: "Peafowl Feathers", icon: "Peafowl_Feathers"}},
    {id: "Any", name: "🗡️  Anya Melfissa", weapon: {name: "Keris", icon: "Keris"}},
    {id: "Kob", name: "🌊 Kobo Kanaeru", weapon: {name: "Umbrella", icon: "Umbrella"}},
    {id: "Kae", name: "🐧 Kaela Kovalskia", weapon: {name: "Blacksmith Hammer", icon: "Blacksmith_Hammer"}},
    {id: "Ves", name: "🔫 Vestia Zeta", weapon: {name: "Silencer Pistol", icon: "Silencer_Pistol"}},
]

export const weapons = [
    {id: "Spi", name: "Spider Cooking", icon: "Spider_Cooking"},
    {id: "ElB", name: "Elite Lava Bucket", icon: "Elite_Lava_Bucket"},
    {id: "CEO", name: "CEO's Tears", icon: "CEOs_Tears"},
    {id: "Wam", name: "Wamy Water", icon: "Wamy_Water"},
    {id: "HoB", name: "Holo Bomb", icon: "Holo_Bomb"},
    {id: "Psy", name: "Psycho Axe", icon: "Psycho_Axe"},
    {id: "BLB", name: "BL Book", icon: "BL_Book"},
    {id: "Cut", name: "Cutting Board", icon: "Cutting_Board"},
    {id: "Fan", name: "Fan Beam", icon: "Fan_Beam"},
    {id: "Plu", name: "Plug Type Asacoco", icon: "Plug_Type_Asacoco"},
    {id: "Glo", name: "Glowstick", icon: "Glowstick"},
    {id: "XPo", name: "X-Potato", icon: "X-Potato"},
    {id: "IdS", name: "Idol Song", icon: "Idol_Song"},
    {id: "ENC", name: "EN's Curse", icon: "ENs_Curse"},
    {id: "Bou", name: "Bounce Ball", icon: "Bounce_Ball"},
    {id: "Sau", name: "Sausage", icon: "Sausage"},

    {id: "Abs", name: "Absolute Wall", icon: "Absolute_Wall", weapons: ["Bou", "Cut"]},
    {id: "BLF", name: "BL Fujoshi", icon: "BL_Fujoshi", weapons: ["BLB", "Psy"]},
    {id: "Bon", name: "Bone Bros.", icon: "Bone_Bros", weapons: ["Cut", "ENC"]},
    {id: "Bre", name: "Breathe-In Type Asacoco", icon: "Breathe-In_Type_Asacoco", weapons: ["HoB", "Plu"]},
    {id: "Bro", name: "Broken Dreams", icon: "Broken_Dreams", weapons: ["CEO", "Spi"]},
    {id: "Cre", name: "Crescent Bardiche", icon: "Crescent_Bardiche", weapons: ["IdS", "Psy"]},
    {id: "Cur", name: "Curse Ball", icon: "Curse_Ball", weapons: ["Bou", "ENC"]},
    {id: "Dra", name: "Dragon Fire", icon: "Dragon_Fire", weapons: ["Fan", "Plu"]},
    {id: "Eld", name: "Eldritch Horror", icon: "Eldritch_Horror", weapons: ["ENC", "Spi"]},
    {id: "ElC", name: "Elite Cooking", icon: "Elite_Cooking", weapons: ["ElB", "Spi"]},
    {id: "Fla", name: "Flattening Board", icon: "Flattening_Board", weapons: ["Cut", "HoB"]},
    {id: "Fro", name: "Frozen Sea", icon: "Frozen_Sea", weapons: ["BLB", "Wam"]},
    {id: "IdC", name: "Idol Concert", icon: "Idol_Concert", weapons: ["Glo", "IdS"]},
    {id: "ImD", name: "I'm Die, Thank You Forever", icon: "Im_Die_Thank_You_Forever", weapons: ["HoB", "XPo"]},
    {id: "Leg", name: "Legendary Sausage", icon: "Legendary_Sausage", weapons: ["BLB", "Sau"]},
    {id: "LiB", name: "Light Beam", icon: "Light_Beam", weapons: ["Fan", "Glo"]},
    {id: "LiW", name: "Lightning Wiener", icon: "Lightning_Wiener", weapons: ["Plu", "Sau"]},
    {id: "MiC", name: "MiComet", icon: "MiComet", weapons: ["ElB", "Psy"]},
    {id: "MiK", name: "MiKorone", icon: "MiKorone", weapons: ["ElB", "XPo"]},
    {id: "Rap", name: "Rap Dog", icon: "Rap_Dog", weapons: ["IdS", "XPo"]},
    {id: "Rin", name: "Ring Of Fitness", icon: "Ring_Of_Fitness", weapons: ["Bou", "CEO"]},
    {id: "SnF", name: "Snow Flower Sake", icon: "Snow_Flower_Sake", weapons: ["Glo", "Wam"]},
    {id: "Str", name: "Stream of Tears", icon: "Stream_of_Tears", weapons: ["CEO", "Fan"]},

    {id: "HoF", name: "Holy Fire", icon: "Holy_Fire", weapons: ["Dra", "Fan", "Plu"], item: "Gor"},
    {id: "IdL", name: "Idol Live", icon: "Idol_Live", weapons: ["IdC", "Glo", "Ids"], item: "Ido"},
    {id: "Jin", name: "Jingisukan", icon: "Jingisukan", weapons: ["ElC", "ElB", "Spi"], item: "Ube"},
    {id: "SnQ", name: "Snow Queen", icon: "Snow_Queen", weapons: ["SnF", "Glo", "Wam"], item: "Sak"},
]

export const items = [
    {id: "Sak", name: "Sake", icon: "Sake"},
    {id: "Lim", name: "Limiter", icon: "Limiter"},
    {id: "Bod", name: "Body Pillow", icon: "Body_Pillow"},
    {id: "Inj", name: "Injection Type Asacoco", icon: "Injection_Type_Asacoco"},
    {id: "Cre", name: "Credit Card", icon: "Credit_Card"},
    {id: "Hal", name: "Halu", icon: "Halu"},
    {id: "Kni", name: "Knightly Milk", icon: "Knightly_Milk"},
    {id: "Fac", name: "Face Mask", icon: "Face_Mask"},
    {id: "Plu", name: "Plushie", icon: "Plushie"},
    {id: "Nur", name: "Nurse's Horn", icon: "Nurses_Horn"},
    {id: "Ful", name: "Full Meal", icon: "Full_Meal"},
    {id: "Mem", name: "Membership", icon: "Membership"},
    {id: "Pik", name: "Piki Piki Piman", icon: "Piki_Piki_Piman"},
    {id: "Hea", name: "Headphones", icon: "Headphones"},
    {id: "Chi", name: "Chicken's Feather", icon: "Chickens_Feather"},
    {id: "Gor", name: "Gorilla's Paw", icon: "Gorillas_Paw"},
    {id: "Ube", name: "Uber Sheep", icon: "Uber_Sheep"},
    {id: "Ido", name: "Idol Costume", icon: "Idol_Costume"},
    {id: "Sto", name: "Stolen Piggy Bank", icon: "Stolen_Piggy_Bank"},
    {id: "Stu", name: "Study Glasses", icon: "Study_Glasses"},
    {id: "Jus", name: "Just Bandage", icon: "Just_Bandage"},
    {id: "GWS", name: "GWS Pill", icon: "GWS_Pill"},
    {id: "Sup", name: "Super Chatto Time!", icon: "Super_Chatto_Time"},
    {id: "Bre", name: "Breastplate", icon: "Breastplate"},
    {id: "Hop", name: "Hope Soda", icon: "Hope_Soda"},
    {id: "Kus", name: "Kusogaki Shackles", icon: "Kusogaki_Shackles"},
    {id: "Dev", name: "Devil Hat", icon: "Devil_Hat"},
    {id: "Bla", name: "Blacksmith's Gear", icon: "Blacksmiths_Gear"},
    {id: "Foc", name: "Focus Shades", icon: "Focus_Shades"},
    {id: "Nin", name: "Ninja Headband", icon: "Ninja_Headband"},
    {id: "Res", name: "Researcher's Coat", icon: "Researchers_Coat"},
    {id: "Can", name: "Candy Kingdom Sweets", icon: "Candy_Kingdom_Sweets"},
    {id: "Bee", name: "Beetle", icon: "Beetle"},
]

export const stamps = [
    {id: "ATK", name: "ATK Up Stamp", icon: "ATK_Up_Stamp"},
    {id: "Bom", name: "Bomb Stamp", icon: "Bomb_Stamp"},
    {id: "Col", name: "Cold Stamp", icon: "Cold_Stamp"},
    {id: "Cri", name: "Crit Up Stamp", icon: "Crit_Up_Stamp"},
    {id: "Gre", name: "Greed Stamp", icon: "Greed_Stamp"},
    {id: "Has", name: "Haste Up Stamp", icon: "Haste_Up_Stamp"},
    {id: "Kno", name: "Knockback Stamp", icon: "Knockback_Stamp"},
    {id: "Lif", name: "Life Steal Stamp", icon: "Life_Steal_Stamp"},
    {id: "Lig", name: "Lightness Stamp", icon: "Lightness_Stamp"},
    {id: "Mar", name: "Marking Stamp", icon: "Marking_Stamp"},
    {id: "Pac", name: "Pacifist Stamp", icon: "Pacifist_Stamp"},
    {id: "Pro", name: "Projectile Up Stamp", icon: "Projectile_Up_Stamp"},
    {id: "Rev", name: "Reverse Stamp", icon: "Reverse_Stamp"},
    {id: "RGB", name: "RGB Stamp", icon: "RGB_Stamp"},
    {id: "Siz", name: "Size Up Stamp", icon: "Size_Up_Stamp"},
    {id: "Slo", name: "Slow Stamp", icon: "Slow_Stamp"},
    {id: "Sol", name: "Solo Stamp", icon: "Solo_Stamp"},
    {id: "Tru", name: "Trumpet Stamp", icon: "Trumpet_Stamp"},
    {id: "Uni", name: "Unit Stamp", icon: "Unit_Stamp"},
    {id: "Wea", name: "Weaken Stamp", icon: "Weaken_Stamp"},
]
