
export const characters = [
    {id: "Ame", name: "Amelia Watson", weapon: "Pistol Shot"},
    {id: "Gaw", name: "Gawr Gura", weapon: "Trident Thrust"},
    {id: "Nin", name: "Ninomae Ina'nis", weapon: "Summon Tentacle"},
    {id: "Tak", name: "Takanashi Kiara", weapon: "Phoenix Sword"},
    {id: "Cal", name: "Calliope Mori", weapon: "Scythe Swing"},
    {id: "Hak", name: "Hakos Baelz", weapon: "Play Dice"},
    {id: "Our", name: "Ouro Kronii", weapon: "Clock Hands"},
    {id: "Cer", name: "Ceres Fauna", weapon: "Nature"},
    {id: "Nan", name: "Nanashi Mumei", weapon: "Bird Feather"},
    {id: "Tsu", name: "Tsukumo Sana", weapon: "Orbit"},
    {id: "IRy", name: "IRyS", weapon: "Nephilim Blast"},
    {id: "Shi", name: "Shirakima Fubuki", weapon: "Fox Tail"},
    {id: "Ook", name: "Ookami Mio", weapon: "Tarot Cards"},
    {id: "Nek", name: "Nekomata Okayu", weapon: "Onigiri"},
    {id: "Ing", name: "Inugami Korone", weapon: "Orayo!"},
    {id: "Tok", name: "Tokino Sora", weapon: "Bright Star"},
    {id: "AZK", name: "AZKi", weapon: "Dive Song"},
    {id: "Rob", name: "Roboco-san", weapon: "Hi-Spec Pistol"},
    {id: "Hos", name: "Hoshimachi Suisei", weapon: "Axe Swing"},
    {id: "Sak", name: "Sakura Miko", weapon: "Sakura Gohei"},
    {id: "Aka", name: "Akai Haato", weapon: "Red Heart"},
    {id: "Yaz", name: "Yazora Mel", weapon: "Kapu Kapu"},
    {id: "Nat", name: "Natsuiro Matsuri", weapon: "Ebifrion"},
    {id: "Aki", name: "Aki Rosenthal", weapon: "Aik"},
    {id: "Ooz", name: "Oozora Subaru", weapon: "Baseball Pitch"},
    {id: "Yuz", name: "Yuzuki Choco", weapon: "Love Needle"},
    {id: "Mur", name: "Murasaki Shion", weapon: "Murasaki Bolt"},
    {id: "Nak", name: "Nakiri Ayame", weapon: "Dual Katana"},
    {id: "Min", name: "Minato Aqua", weapon: "Cleaning Broom"},
    {id: "Air", name: "Airani lofifteen", weapon: "Paint Brush"},
    {id: "Moo", name: "Moona Hoshinova", weapon: "Crescent Moon"},
    {id: "Ayu", name: "Ayunda Risu", weapon: "Nuts"},
    {id: "Kur", name: "Kureiji Ollie", weapon: "Path of Sincerity"},
    {id: "Pav", name: "Pavolia Reine", weapon: "Peafowl Feathers"},
    {id: "Any", name: "Anya Melfissa", weapon: "Keris"},
    {id: "Kob", name: "Kobo Kanaeru", weapon: "Umbrella"},
    {id: "Kae", name: "Kaela Kovalskia", weapon: "Blacksmith Hammer"},
    {id: "Ves", name: "Vestia Zeta", weapon: "Silencer Pistol"},
]

export const weapons = [
    {id: "Spi", name: "Spider Cooking", icon: "Spider_Cooking", weapons: ["Bro", "Eld", "ElC", "Jin"]},
    {id: "ElB", name: "Elite Lava Bucket", icon: "Elite_Lava_Bucket", weapons: ["ElC", "MiC", "Mik", "Jin"]},
    {id: "CEO", name: "CEO's Tears", icon: "CEOs_Tears", weapons: ["Bro", "Rin", "Str"]},
    {id: "Wam", name: "Wamy Water", icon: "Wamy_Water", weapons: ["Fro", "SnF", "SnQ"]},
    {id: "HoB", name: "Holo Bomb", icon: "Holo_Bomb", weapons: ["Bre", "Fla", "ImD"]},
    {id: "Psy", name: "Psycho Axe", icon: "Psycho_Axe", weapons: ["BLF", "Cre", "MiC"]},
    {id: "BLB", name: "BL Book", icon: "BL_Book", weapons: ["BLF", "Fro", "Leg"]},
    {id: "Cut", name: "Cutting Board", icon: "Cutting_Board", weapons: ["Abs", "Bon", "Fla"]},
    {id: "Fan", name: "Fan Beam", icon: "Fan_Beam", weapons: ["Dra", "LiB", "Str", "HoF"]},
    {id: "Plu", name: "Plug Type Asacoco", icon: "Plug_Type_Asacoco", weapons: ["Bre", "Dra", "LiW", "HoF"]},
    {id: "Glo", name: "Glowstick", icon: "Glowstick", weapons: ["IdC", "LiB", "SnF", "IdL", "SnQ"]},
    {id: "XPo", name: "X-Potato", icon: "X-Potato", weapons: ["ImD", "MiK", "Rap"]},
    {id: "IdS", name: "Idol Song", icon: "Idol_Song", weapons: ["Cre", "IdC", "Rap", "IdL"]},
    {id: "ENC", name: "EN's Curse", icon: "ENs_Curse", weapons: ["Bon", "Cur", "Eld"]},
    {id: "Bou", name: "Bounce Ball", icon: "Bounce_Ball", weapons: ["Abs", "Cur", "Rin"]},
    {id: "Sau", name: "Sausage", icon: "Sausage", weapons: ["Leg", "LiW"]},

    {id: "Abs", name: "Absolute Wall", icon: "Absolute_Wall", weapons: ["Bou", "Cut"]},
    {id: "BLF", name: "BL Fujoshi", icon: "BL_Fujoshi", weapons: ["BLB", "Psy"]},
    {id: "Bon", name: "Bone Bros.", icon: "Bone_Bros", weapons: ["Cut", "ENC"]},
    {id: "Bre", name: "Breathe-In Type Asacoco", icon: "Breathe-In_Type_Asacoco", weapons: ["HoB", "Plu"]},
    {id: "Bro", name: "Broken Dreams", icon: "Broken_Dreams", weapons: ["CEO", "Spi"]},
    {id: "Cre", name: "Crescent Bardiche", icon: "Crescent_Bardiche", weapons: ["IdS", "Psy"]},
    {id: "Cur", name: "Curse Ball", icon: "Curse_Ball", weapons: ["Bou", "ENC"]},
    {id: "Dra", name: "Dragon Fire", icon: "Dragon_Fire", weapons: ["Fan", "Plu", "HoF"]},
    {id: "Eld", name: "Eldritch Horror", icon: "Eldritch_Horror", weapons: ["ENC", "Spi"]},
    {id: "ElC", name: "Elite Cooking", icon: "Elite_Cooking", weapons: ["ElB", "Spi", "Jin"]},
    {id: "Fla", name: "Flattening Board", icon: "Flattening_Board", weapons: ["Cut", "HoB"]},
    {id: "Fro", name: "Frozen Sea", icon: "Frozen_Sea", weapons: ["BLB", "Wam"]},
    {id: "IdC", name: "Idol Concert", icon: "Idol_Concert", weapons: ["Glo", "IdS", "IdL"]},
    {id: "ImD", name: "I'm Die, Thank You Forever", icon: "Im_Die_Thank_You_Forever", weapons: ["HoB", "XPo"]},
    {id: "Leg", name: "Legendary Sausage", icon: "Legendary_Sausage", weapons: ["BLB", "Sau"]},
    {id: "LiB", name: "Light Beam", icon: "Light_Beam", weapons: ["Fan", "Glo"]},
    {id: "LiW", name: "Lightning Wiener", icon: "Lightning_Wiener", weapons: ["Plu", "Sau"]},
    {id: "MiC", name: "MiComet", icon: "MiComet", weapons: ["ElB", "Psy"]},
    {id: "MiK", name: "MiKorone", icon: "MiKorone", weapons: ["ElB", "XPo"]},
    {id: "Rap", name: "Rap Dog", icon: "Rap_Dog", weapons: ["IdS", "XPo"]},
    {id: "Rin", name: "Ring Of Fitness", icon: "Ring_Of_Fitness", weapons: ["Bou", "CEO"]},
    {id: "SnF", name: "Snow Flower Sake", icon: "Snow_Flower_Sake", weapons: ["Glo", "Wam", "SnQ"]},
    {id: "Str", name: "Stream of Tears", icon: "Stream_of_Tears", weapons: ["CEO", "Fan"]},

    {id: "HoF", name: "Holy Fire", icon: "Holy_Fire", weapons: ["Dra", "Fan", "Plu"], item: "Gor"},
    {id: "IdL", name: "Idol Live", icon: "Idol_Live", weapons: ["IdC", "Glo", "IdS"], item: "Ido"},
    {id: "Jin", name: "Jingisukan", icon: "Jingisukan", weapons: ["ElC", "ElB", "Spi"], item: "Ube"},
    {id: "SnQ", name: "Snow Queen", icon: "Snow_Queen", weapons: ["SnF", "Glo", "Wam"], item: "Sak"},
]

export const items = [
    {id: "Sak", name: "Sake", icon: "Sake"},
    {id: "Lim", name: "Limiter", icon: "Limiter"},
    {id: "Bod", name: "Body Pillow", icon: "Body_Pillow"},
    {id: "Inj", name: "Injection Type Asacoco", icon: "Injection_Type_Asacoco"},
    {id: "Cre", name: "Credit Card", icon: "Credit_Card"},
    {id: "Hal", name: "Halu", icon: "Halu"},
    {id: "Kni", name: "Knightly Milk", icon: "Knightly_Milk"},
    {id: "Fac", name: "Face Mask", icon: "Face_Mask"},
    {id: "Plu", name: "Plushie", icon: "Plushie"},
    {id: "Nur", name: "Nurse's Horn", icon: "Nurses_Horn"},
    {id: "Ful", name: "Full Meal", icon: "Full_Meal"},
    {id: "Mem", name: "Membership", icon: "Membership"},
    {id: "Pik", name: "Piki Piki Piman", icon: "Piki_Piki_Piman"},
    {id: "Hea", name: "Headphones", icon: "Headphones"},
    {id: "Chi", name: "Chicken's Feather", icon: "Chickens_Feather"},
    {id: "Gor", name: "Gorilla's Paw", icon: "Gorillas_Paw"},
    {id: "Ube", name: "Uber Sheep", icon: "Uber_Sheep"},
    {id: "Ido", name: "Idol Costume", icon: "Idol_Costume"},
    {id: "Sto", name: "Stolen Piggy Bank", icon: "Stolen_Piggy_Bank"},
    {id: "Stu", name: "Study Glasses", icon: "Study_Glasses"},
    {id: "Jus", name: "Just Bandage", icon: "Just_Bandage"},
    {id: "GWS", name: "GWS Pill", icon: "GWS_Pill"},
    {id: "Sup", name: "Super Chatto Time!", icon: "Super_Chatto_Time"},
    {id: "Bre", name: "Breastplate", icon: "Breastplate"},
    {id: "Hop", name: "Hope Soda", icon: "Hope_Soda"},
    {id: "Kus", name: "Kusogaki Shackles", icon: "Kusogaki_Shackles"},
    {id: "Dev", name: "Devil Hat", icon: "Devil_Hat"},
    {id: "Bla", name: "Blacksmith's Gear", icon: "Blacksmiths_Gear"},
    {id: "Foc", name: "Focus Shades", icon: "Focus_Shades"},
    {id: "Nin", name: "Ninja Headband", icon: "Ninja_Headband"},
    {id: "Res", name: "Researcher's Coat", icon: "Researchers_Coat"},
    {id: "Can", name: "Candy Kingdom Sweets", icon: "Candy_Kingdom_Sweets"},
    {id: "Bee", name: "Beetle", icon: "Beetle"},
]

export const stamps = [
    {id: "ATK", name: "ATK Up Stamp"},
    {id: "Bom", name: "Bomb Stamp"},
    {id: "Col", name: "Cold Stamp"},
    {id: "Cri", name: "Crit Up Stamp"},
    {id: "Gre", name: "Greed Stamp"},
    {id: "Has", name: "Haste Up Stamp"},
    {id: "Kno", name: "Knockback Stamp"},
    {id: "Lif", name: "Life Steal Stamp"},
    {id: "Lig", name: "Lightness Stamp"},
    {id: "Mar", name: "Marking Stamp"},
    {id: "Pac", name: "Pacifist Stamp"},
    {id: "Pro", name: "Projectile Up Stamp"},
    {id: "Rev", name: "Reverse Stamp"},
    {id: "RGB", name: "RGB Stamp"},
    {id: "Siz", name: "Size Up Stamp"},
    {id: "Slo", name: "Slow Stamp"},
    {id: "Sol", name: "Solo Stamp"},
    {id: "Tru", name: "Trumpet Stamp"},
    {id: "Uni", name: "Unit Stamp"},
    {id: "Wea", name: "Weaken Stamp"},
]
